---
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: sdi-pids-limit
spec:
  kubeletConfig:
    podPidsLimit: 8192
  machineConfigPoolSelector:
    matchLabels:
      workload: sapdataintelligence