# permissions for end users to view sdiobservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdiobserver-viewer-role
rules:
- apiGroups:
  - di.sap-cop.redhat.com
  resources:
  - sdiobservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - di.sap-cop.redhat.com
  resources:
  - sdiobservers/status
  verbs:
  - get
