# permissions for end users to edit sdiobservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sdiobserver-editor-role
rules:
- apiGroups:
  - di.sap-cop.redhat.com
  resources:
  - sdiobservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - di.sap-cop.redhat.com
  resources:
  - sdiobservers/status
  verbs:
  - get
