apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sdi-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sdi-anyuid
subjects:
  - kind: Group
    name: system:serviceaccounts:sdi
    namespace: sdi