apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sdi-privileged
  namespace: sdi-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sdi-privileged
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sdi-observer